name: MSVC Build All Archs

on: [push, pull_request]

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { arch: x86, platform: Win32 }
          - { arch: x64, platform: x64 }
          - { arch: arm64, platform: ARM64 }

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Build Shared
        run: |
          cmake -B build-shared -A ${{ matrix.platform }} -DBUILD_SHARED_LIBS=ON
          cmake --build build-shared --config Release
          
      - name: Build Static
        run: |
          cmake -B build-static -A ${{ matrix.platform }} -DBUILD_SHARED_LIBS=OFF
          cmake --build build-static --config Release

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libserialport-${{ matrix.arch }}
          path: |
            build-shared/Release/*.dll
            build-shared/Release/*.lib
            build-shared/Release/*.exe
            build-static/Release/*.lib
            build-static/Release/*.exe
